//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.WebFresher042023.Demo.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceVN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceVN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.WebFresher042023.Demo.Common.Resources.ResourceVN", typeof(ResourceVN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã tài khoản.
        /// </summary>
        public static string AccountCode {
            get {
                return ResourceManager.GetString("AccountCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tính chất.
        /// </summary>
        public static string AccountFeature {
            get {
                return ResourceManager.GetString("AccountFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày hạch toán.
        /// </summary>
        public static string AccountingDate {
            get {
                return ResourceManager.GetString("AccountingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hạch toán kinh tế.
        /// </summary>
        public static string Accountings {
            get {
                return ResourceManager.GetString("Accountings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài khoản.
        /// </summary>
        public static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tiếng anh.
        /// </summary>
        public static string AccountNameEnglish {
            get {
                return ResourceManager.GetString("AccountNameEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tiền nợ.
        /// </summary>
        public static string AccountOfDebt {
            get {
                return ResourceManager.GetString("AccountOfDebt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạm ứng cho nhân viên.
        /// </summary>
        public static string AdvanceForEmployees {
            get {
                return ResourceManager.GetString("AdvanceForEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tài khoản ngân hàng.
        /// </summary>
        public static string BankAccount {
            get {
                return ResourceManager.GetString("BankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên chi nhánh.
        /// </summary>
        public static string BankBranch {
            get {
                return ResourceManager.GetString("BankBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉnh/thành phố của ngân hàng.
        /// </summary>
        public static string BankCity {
            get {
                return ResourceManager.GetString("BankCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên ngân hàng.
        /// </summary>
        public static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi mua ngoài có hóa đơn.
        /// </summary>
        public static string BuyOutsideWithInvoice {
            get {
                return ResourceManager.GetString("BuyOutsideWithInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng ban.
        /// </summary>
        public static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi tiền vào ngân hàng.
        /// </summary>
        public static string DepositMoneyInTheBank {
            get {
                return ResourceManager.GetString("DepositMoneyInTheBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số ngày được nợ.
        /// </summary>
        public static string DueTime {
            get {
                return ResourceManager.GetString("DueTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email người nhận hóa đơn.
        /// </summary>
        public static string EmailReceiverBill {
            get {
                return ResourceManager.GetString("EmailReceiverBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên.
        /// </summary>
        public static string EmployeeCode {
            get {
                return ResourceManager.GetString("EmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diễn giải.
        /// </summary>
        public static string Explain {
            get {
                return ResourceManager.GetString("Explain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nữ.
        /// </summary>
        public static string FeMale {
            get {
                return ResourceManager.GetString("FeMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        public static string Fullname {
            get {
                return ResourceManager.GetString("Fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên người nhận hóa đơn.
        /// </summary>
        public static string FullnameReceiverBill {
            get {
                return ResourceManager.GetString("FullnameReceiverBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới tính.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm nhà cung cấp.
        /// </summary>
        public static string GroupSuppliersId {
            get {
                return ResourceManager.GetString("GroupSuppliersId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số chứng minh thư.
        /// </summary>
        public static string IdentityNumber {
            get {
                return ResourceManager.GetString("IdentityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nơi cấp.
        /// </summary>
        public static string IdentityPlaceRelease {
            get {
                return ResourceManager.GetString("IdentityPlaceRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Là khách hàng.
        /// </summary>
        public static string IsCustomer {
            get {
                return ResourceManager.GetString("IsCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Là nhà cung cấp.
        /// </summary>
        public static string IsSupplier {
            get {
                return ResourceManager.GetString("IsSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đại diện pháp luật.
        /// </summary>
        public static string LegalRepresentative {
            get {
                return ResourceManager.GetString("LegalRepresentative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số nợ tối đa.
        /// </summary>
        public static string MaxAccountOfDebt {
            get {
                return ResourceManager.GetString("MaxAccountOfDebt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại di động.
        /// </summary>
        public static string MobilePhoneNumber {
            get {
                return ResourceManager.GetString("MobilePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tiền.
        /// </summary>
        public static string Money {
            get {
                return ResourceManager.GetString("Money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        public static string NumberOrder {
            get {
                return ResourceManager.GetString("NumberOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khác.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi khác.
        /// </summary>
        public static string OtherSpending {
            get {
                return ResourceManager.GetString("OtherSpending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản tổng hợp.
        /// </summary>
        public static string ParentName {
            get {
                return ResourceManager.GetString("ParentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu chi.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số phiếu chi.
        /// </summary>
        public static string PaymentCode {
            get {
                return ResourceManager.GetString("PaymentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày phiếu chi.
        /// </summary>
        public static string PaymentDate {
            get {
                return ResourceManager.GetString("PaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trả lương nhân viên.
        /// </summary>
        public static string PaySalaryForEmployees {
            get {
                return ResourceManager.GetString("PaySalaryForEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trả tiền nhà cung cấp (không theo hóa đơn).
        /// </summary>
        public static string PaySuppliersNotBilled {
            get {
                return ResourceManager.GetString("PaySuppliersNotBilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại cố định.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại người nhận hóa đơn.
        /// </summary>
        public static string PhoneNumberReceiverBill {
            get {
                return ResourceManager.GetString("PhoneNumberReceiverBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức danh.
        /// </summary>
        public static string PositionName {
            get {
                return ResourceManager.GetString("PositionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại chứng từ.
        /// </summary>
        public static string ReceiptType {
            get {
                return ResourceManager.GetString("ReceiptType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lý do thu/chi.
        /// </summary>
        public static string ResonDepositWithdraw {
            get {
                return ResourceManager.GetString("ResonDepositWithdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng.
        /// </summary>
        public static string Sum {
            get {
                return ResourceManager.GetString("Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà cung cấp.
        /// </summary>
        public static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhà cung cấp.
        /// </summary>
        public static string SupplierCode {
            get {
                return ResourceManager.GetString("SupplierCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhà cung cấp.
        /// </summary>
        public static string SupplierName {
            get {
                return ResourceManager.GetString("SupplierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại nhà cung cấp.
        /// </summary>
        public static string SupplierType {
            get {
                return ResourceManager.GetString("SupplierType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã số thuế.
        /// </summary>
        public static string TaxCode {
            get {
                return ResourceManager.GetString("TaxCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển tiền cho chi nhánh khác.
        /// </summary>
        public static string TransferMoneyToAnotherBranch {
            get {
                return ResourceManager.GetString("TransferMoneyToAnotherBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã tài khoản chỉ chứa chữ và số..
        /// </summary>
        public static string UserMsg_AccountCodeFormat {
            get {
                return ResourceManager.GetString("UserMsg_AccountCodeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tài khoản không hợp lệ. Số tài khoản chi tiết phải bắt đầu bằng số của Tài khoản tổng hợp..
        /// </summary>
        public static string UserMsg_AccountCodeNeedPrefixAccountParentCode {
            get {
                return ResourceManager.GetString("UserMsg_AccountCodeNeedPrefixAccountParentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản &lt;{0}&gt; theo &lt;Nhà cung cấp&gt;, chứng từ hạch toán thiếu &lt;Nhà cung cấp&gt;..
        /// </summary>
        public static string UserMsg_AccountSupplierAndPaymentLackSupplier {
            get {
                return ResourceManager.GetString("UserMsg_AccountSupplierAndPaymentLackSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản cha đang ở trạng thái \&quot;Ngừng sử dụng\&quot;. Bạn không thể thiết lập trạng thái \&quot;Sử dụng\&quot; cho Tài khoản con..
        /// </summary>
        public static string UserMsg_AccountUsingAndParentNotUsing {
            get {
                return ResourceManager.GetString("UserMsg_AccountUsingAndParentNotUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể thay đổi mã nhà cung cấp vì đã phát sinh chứng từ..
        /// </summary>
        public static string UserMsg_CantChangeSupplierCode {
            get {
                return ResourceManager.GetString("UserMsg_CantChangeSupplierCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa nhà cung cấp đã phát sinh chứng từ..
        /// </summary>
        public static string UserMsg_CantDeleteSupplier {
            get {
                return ResourceManager.GetString("UserMsg_CantDeleteSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} chỉ chứa ký tự số.
        /// </summary>
        public static string UserMsg_ContainsOnlyNumber {
            get {
                return ResourceManager.GetString("UserMsg_ContainsOnlyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày hạch toán phải lớn hơn hoặc bằng Ngày chứng từ &lt;{0}&gt;. Xin vui lòng kiểm tra lại..
        /// </summary>
        public static string UserMsg_DateAccountingNeedMoreDatePayment {
            get {
                return ResourceManager.GetString("UserMsg_DateAccountingNeedMoreDatePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh không lớn hơn ngày hiện tại..
        /// </summary>
        public static string UserMsg_DateOfBirth {
            get {
                return ResourceManager.GetString("UserMsg_DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đã phát sinh hạch toán không thể xóa..
        /// </summary>
        public static string UserMsg_DeleteAccountArisingAccounting {
            get {
                return ResourceManager.GetString("UserMsg_DeleteAccountArisingAccounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa không thành công. Không thể xóa danh mục cha nếu chưa xóa danh mục con..
        /// </summary>
        public static string UserMsg_DeleteAccountHasChildren {
            get {
                return ResourceManager.GetString("UserMsg_DeleteAccountHasChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đã được nhà cung cấp sử dụng không thể xóa..
        /// </summary>
        public static string UserMsg_DeleteAccountSupplier {
            get {
                return ResourceManager.GetString("UserMsg_DeleteAccountSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng ban không được để trống..
        /// </summary>
        public static string UserMsg_DepartmentIdEmpty {
            get {
                return ResourceManager.GetString("UserMsg_DepartmentIdEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã tài khoản &lt;{0}&gt; đã tồn tại vui lòng kiểm tra lại..
        /// </summary>
        public static string UserMsg_DupAccountCode {
            get {
                return ResourceManager.GetString("UserMsg_DupAccountCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã &lt;{0}&gt; đã tồn tại. Vui lòng thử lại..
        /// </summary>
        public static string UserMsg_DupCode {
            get {
                return ResourceManager.GetString("UserMsg_DupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên {0}  đã tồn tại lòng kiểm tra lại ..
        /// </summary>
        public static string UserMsg_DupEmployeeCode {
            get {
                return ResourceManager.GetString("UserMsg_DupEmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tài khoản {0} đã đã tồn tại..
        /// </summary>
        public static string UserMsg_DuplicateBankAccountNumber {
            get {
                return ResourceManager.GetString("UserMsg_DuplicateBankAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số chứng từ &lt;{0}&gt; đã tồn tại. Nếu không tìm thấy số chứng từ &lt;{0}&gt;. Vui lòng thực hiện tính năng bảo trì số chứng từ.. Bạn có muốn chương trình tự động tăng số chứng từ không?.
        /// </summary>
        public static string UserMsg_DupPaymentCode {
            get {
                return ResourceManager.GetString("UserMsg_DupPaymentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không được để trống..
        /// </summary>
        public static string UserMsg_EmployeeCodeEmpty {
            get {
                return ResourceManager.GetString("UserMsg_EmployeeCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không đúng định dạng [NV-]&lt;Mã số&gt;..
        /// </summary>
        public static string UserMsg_EmployeeCodeFormat {
            get {
                return ResourceManager.GetString("UserMsg_EmployeeCodeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xảy ra lỗi. Vui lòng liên hệ MS để được trợ giúp..
        /// </summary>
        public static string UserMsg_Exception {
            get {
                return ResourceManager.GetString("UserMsg_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên không được để trống..
        /// </summary>
        public static string UserMsg_FullnameEmpty {
            get {
                return ResourceManager.GetString("UserMsg_FullnameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày cấp không lớn hơn ngày hiện tại..
        /// </summary>
        public static string UserMsg_IdentityDateRelease {
            get {
                return ResourceManager.GetString("UserMsg_IdentityDateRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu hạch toán kinh tế không hợp lệ..
        /// </summary>
        public static string UserMsg_InValdAccounting {
            get {
                return ResourceManager.GetString("UserMsg_InValdAccounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đầu vào không hợp lệ..
        /// </summary>
        public static string UserMsg_InValid {
            get {
                return ResourceManager.GetString("UserMsg_InValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không hợp lệ..
        /// </summary>
        public static string UserMsg_InValidEmail {
            get {
                return ResourceManager.GetString("UserMsg_InValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  phải là môt số nguyên.
        /// </summary>
        public static string UserMsg_IsNumber {
            get {
                return ResourceManager.GetString("UserMsg_IsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không quá {1} ký tự..
        /// </summary>
        public static string UserMsg_MaxLength {
            get {
                return ResourceManager.GetString("UserMsg_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên tối đâ 20 ký tự..
        /// </summary>
        public static string UserMsg_MaxLengthEmployeeCode {
            get {
                return ResourceManager.GetString("UserMsg_MaxLengthEmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tối đa 100 ký tự..
        /// </summary>
        public static string UserMsg_MaxLengthFullName {
            get {
                return ResourceManager.GetString("UserMsg_MaxLengthFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tối thiểu {1} ký tự..
        /// </summary>
        public static string UserMsg_MinLength {
            get {
                return ResourceManager.GetString("UserMsg_MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tiền phải  trong phạm vi -99.999.999.999 đến 99.999.999.999..
        /// </summary>
        public static string UserMsg_MoneyRange {
            get {
                return ResourceManager.GetString("UserMsg_MoneyRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tài khoản có độ dài &gt; 3 ký tự phải điền thông tin &lt;Tài khoản tổng hợp&gt;..
        /// </summary>
        public static string UserMsg_NeedParentAccount {
            get {
                return ResourceManager.GetString("UserMsg_NeedParentAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải nhập chứng từ chi tiết..
        /// </summary>
        public static string UserMsg_NeedTypingAccountingDetail {
            get {
                return ResourceManager.GetString("UserMsg_NeedTypingAccountingDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản chứa tài khoản khác nên không thể thay đổi tài khoản tổng hợp..
        /// </summary>
        public static string UserMsg_NotChangeParentWhenAccountIsParent {
            get {
                return ResourceManager.GetString("UserMsg_NotChangeParentWhenAccountIsParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không được để trống..
        /// </summary>
        public static string UserMsg_NotEmpty {
            get {
                return ResourceManager.GetString("UserMsg_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy tài nguyên..
        /// </summary>
        public static string UserMsg_NotFound {
            get {
                return ResourceManager.GetString("UserMsg_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to không tìm thấy tài khoản..
        /// </summary>
        public static string UserMsg_NotFoundAccount {
            get {
                return ResourceManager.GetString("UserMsg_NotFoundAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy hạch toán kinh tế..
        /// </summary>
        public static string Usermsg_NotFoundAccounting {
            get {
                return ResourceManager.GetString("Usermsg_NotFoundAccounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy tài khoản tổng hợp..
        /// </summary>
        public static string UserMsg_NotFoundAccountParent {
            get {
                return ResourceManager.GetString("UserMsg_NotFoundAccountParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy tài khoản trả.
        /// </summary>
        public static string UserMsg_NotFoundAccountPayable {
            get {
                return ResourceManager.GetString("UserMsg_NotFoundAccountPayable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy tài khoản thu.
        /// </summary>
        public static string UserMsg_NotFoundAccountReceivable {
            get {
                return ResourceManager.GetString("UserMsg_NotFoundAccountReceivable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy nhân viên..
        /// </summary>
        public static string UserMsg_NotFoundEmployee {
            get {
                return ResourceManager.GetString("UserMsg_NotFoundEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy nhân viên mua hàng..
        /// </summary>
        public static string UserMsg_NotFoundEmployeeSupplier {
            get {
                return ResourceManager.GetString("UserMsg_NotFoundEmployeeSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy nhóm nhà cung cấp..
        /// </summary>
        public static string UserMsg_NotFoundGroupSupplier {
            get {
                return ResourceManager.GetString("UserMsg_NotFoundGroupSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy phiếu chi..
        /// </summary>
        public static string UserMsg_NotFoundPayment {
            get {
                return ResourceManager.GetString("UserMsg_NotFoundPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy nhà cung cấp..
        /// </summary>
        public static string UserMsg_NotFoundSupplier {
            get {
                return ResourceManager.GetString("UserMsg_NotFoundSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm điều khoản thanh toán..
        /// </summary>
        public static string UserMsg_NotFoundTermPayment {
            get {
                return ResourceManager.GetString("UserMsg_NotFoundTermPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không được thay đổi số tài khoản vì tài khoản này chứa tài khoản khác trong hệ thống..
        /// </summary>
        public static string UserMsg_NotUpdateAccountWhenParent {
            get {
                return ResourceManager.GetString("UserMsg_NotUpdateAccountWhenParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu chi đã được ghi sổ. Vui lòng kiểm tra lại..
        /// </summary>
        public static string UserMsg_PaymentWritten {
            get {
                return ResourceManager.GetString("UserMsg_PaymentWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu chi đã ghi sổ không thể xóa..
        /// </summary>
        public static string UserMsg_PaymentWrittenDontDelete {
            get {
                return ResourceManager.GetString("UserMsg_PaymentWrittenDontDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} có phạm vi từ  {1} đến {2} ..
        /// </summary>
        public static string UserMsg_Range {
            get {
                return ResourceManager.GetString("UserMsg_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà cung cấp đã có phát sinh..
        /// </summary>
        public static string UserMsg_SupplierHasArisen {
            get {
                return ResourceManager.GetString("UserMsg_SupplierHasArisen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đã phát sinh hạch toán không thể sửa..
        /// </summary>
        public static string UserMsg_UpdateAccountArisingAccounting {
            get {
                return ResourceManager.GetString("UserMsg_UpdateAccountArisingAccounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường {0} nhập sai dữ liệu..
        /// </summary>
        public static string UserMsg_WrongInput {
            get {
                return ResourceManager.GetString("UserMsg_WrongInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xưng hô.
        /// </summary>
        public static string Vocative {
            get {
                return ResourceManager.GetString("Vocative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
    }
}
